# Generated by Django 5.2.7 on 2025-11-07 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, help_text='Upload banner section video file...', null=True, upload_to='videos/', verbose_name='Video')),
                ('title', models.CharField(blank=True, help_text='Enter your banner title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title')),
            ],
        ),
    ]
