# Generated by Django 5.2.7 on 2025-11-07 09:44

import django.core.validators
import utils.validate_image_extension
import utils.validate_image_size
import utils.validate_video_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='company_profile_name',
            field=models.CharField(blank=True, help_text='Enter company profile button name...', max_length=180, null=True, verbose_name='Company Profile Button Name'),
        ),
        migrations.AddField(
            model_name='banner',
            name='company_profile_url',
            field=models.URLField(blank=True, help_text='Enter company profile button URL...', max_length=180, null=True, verbose_name='Company Profile Button URL'),
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, help_text='Enter your banner description...', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='banner',
            name='get_started_name',
            field=models.CharField(blank=True, help_text='Enter get started button name...', max_length=180, null=True, verbose_name='Get Started Button Name'),
        ),
        migrations.AddField(
            model_name='banner',
            name='get_started_url',
            field=models.URLField(blank=True, help_text='Enter get started button URL...', max_length=180, null=True, verbose_name='Get Started Button URL'),
        ),
        migrations.AddField(
            model_name='banner',
            name='payment_logo',
            field=models.ImageField(blank=True, help_text='Upload your payment logo...', null=True, upload_to='banner/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Paymnet Logo'),
        ),
        migrations.AddField(
            model_name='banner',
            name='secure_business_name',
            field=models.CharField(blank=True, help_text='Enter secure my business button name...', max_length=180, null=True, verbose_name='Secure My Business Button Name'),
        ),
        migrations.AddField(
            model_name='banner',
            name='secure_business_url',
            field=models.URLField(blank=True, help_text='Enter secure my business button URL...', max_length=180, null=True, verbose_name='Secure My Business Button URL'),
        ),
        migrations.AddField(
            model_name='banner',
            name='short_description',
            field=models.TextField(blank=True, help_text='Enter your banner short description...', null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='banner',
            name='sub_title',
            field=models.CharField(blank=True, help_text='Enter your banner sub title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload banner section video file...', null=True, upload_to='videos/', validators=[utils.validate_video_size.VALIDATE_VIDEO_SIZE], verbose_name='Video'),
        ),
    ]
