# Generated by Django 5.2.7 on 2025-11-07 11:01

import utils.validate_image_extension
import utils.validate_image_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_banner_company_profile_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.ImageField(blank=True, help_text='Upload your security firm bg image...', null=True, upload_to='security-firm/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Security Firm BG')),
                ('title_span', models.CharField(blank=True, help_text='This part will be wrapped in <span> in frontend', max_length=280, null=True, verbose_name='Title (span part)')),
                ('title_normal', models.CharField(blank=True, help_text='This part will be outside <span> in frontend', max_length=280, null=True, verbose_name='Title (normal part)')),
                ('main_img', models.ImageField(blank=True, help_text='Upload your security firm image...', null=True, upload_to='security-firm/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Main Image')),
                ('sub_img', models.ImageField(blank=True, help_text='Upload your security firm image...', null=True, upload_to='security-firm/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Main Image')),
                ('left_side_animation_img', models.ImageField(blank=True, help_text='Upload your security firm left side animation image...', null=True, upload_to='security-firm/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Left side animation image')),
                ('right_side_animation_img', models.ImageField(blank=True, help_text='Upload your security firm right side animation image...', null=True, upload_to='security-firm/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Right side animation image')),
                ('mission_title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Mission Title')),
                ('mission_description', models.TextField(blank=True, null=True, verbose_name='Mission description')),
                ('vision_title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Vision Title')),
                ('vision_description', models.TextField(blank=True, null=True, verbose_name='Vision description')),
                ('get_to_know_us_btn_name', models.CharField(blank=True, help_text='Enter get to know us button name...', max_length=180, null=True, verbose_name='Get To Know Us Button Name')),
                ('get_to_know_us_btn_url', models.URLField(blank=True, help_text='Enter get to know us button URL...', max_length=180, null=True, verbose_name='Get To Know Us Button URL')),
                ('security_persentences', models.IntegerField(default=0, verbose_name='Security Persentences')),
                ('ability_persentences', models.IntegerField(default=0, verbose_name='Security Persentences')),
                ('solving_persentences', models.IntegerField(default=0, verbose_name='Security Persentences')),
            ],
        ),
    ]
