# Generated by Django 5.2.7 on 2025-11-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_cybersecuritysolutionitem_cybersecuritysolutiontitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybersecuritysolutionitem',
            name='count',
            field=models.IntegerField(default=0, help_text='Enter cyber security solution item count...', verbose_name='Cyber Security Solution Item Count'),
        ),
        migrations.AddField(
            model_name='cybersecuritysolutionitem',
            name='title',
            field=models.CharField(blank=True, help_text='Enter cyber security solution item title...', max_length=280, null=True, verbose_name='Cyber Security Solution Item Title'),
        ),
        migrations.AddField(
            model_name='cybersecuritysolutiontitle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Cyber Security Solution Description'),
        ),
        migrations.AddField(
            model_name='cybersecuritysolutiontitle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cyber-ecurity/', verbose_name='Cyber Security Solution Image'),
        ),
        migrations.AlterField(
            model_name='cybersecuritysolutionitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload cyber security solution item image...', null=True, upload_to='cybers-ecurity/', verbose_name='Cyber Security Solution Item Image'),
        ),
        migrations.AlterField(
            model_name='cybersecuritysolutiontitle',
            name='title',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Cyber Security Solution Title'),
        ),
    ]
