# Generated by Django 5.2.7 on 2025-11-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_cybersecuritysolutionitem_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProvenProcessSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='our-proven-process-security/', verbose_name='our proven process security image')),
                ('title_before_span', models.CharField(blank=True, help_text='Enter your our proven process security before span...', max_length=280, null=True, verbose_name='our proven process security title before span')),
                ('title_span', models.CharField(blank=True, help_text='Enter your our proven process security title span...', max_length=280, null=True, verbose_name='our proven process security title span')),
                ('title_after_span', models.CharField(blank=True, help_text='Enter your our proven process security title after span...', max_length=280, null=True, verbose_name='our proven process security title after span')),
                ('description', models.TextField(blank=True, null=True, verbose_name='our proven process security description')),
            ],
        ),
        migrations.CreateModel(
            name='OurProvenProcessSecurityItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='our-proven-process-security/', verbose_name='our proven process security item image')),
                ('title', models.CharField(blank=True, max_length=280, null=True, verbose_name='our proven process security item title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='our proven process security item description')),
            ],
        ),
    ]
