# Generated by Django 5.2.7 on 2025-11-07 07:14

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your website page name...', max_length=180, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Page Name')),
                ('slug', models.SlugField(editable=False, max_length=180, unique=True, verbose_name='Page Slug')),
                ('content', ckeditor.fields.RichTextField(help_text='Enter your website page content...', verbose_name='Page description')),
                ('seo_title', models.CharField(blank=True, help_text='SEO Title of the page for search engines', max_length=255, null=True, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, help_text='SEO description of the page for search engines', null=True, verbose_name='SEO Description')),
                ('seo_canonical', models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content', null=True, verbose_name='Canonical URL')),
                ('seo_author', models.CharField(blank=True, help_text='Author name for SEO purposes', max_length=255, null=True, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='SEOKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='SEO keyword or phrase', max_length=255, unique=True, verbose_name='Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='OpenGraphMetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Open Graph Title for social media', max_length=255, null=True, verbose_name='OG Title')),
                ('description', models.TextField(blank=True, help_text='Open Graph Description for social media', null=True, verbose_name='OG Description')),
                ('url', models.URLField(blank=True, help_text='URL for Open Graph sharing', null=True, verbose_name='OG URL')),
                ('type', models.CharField(default='website', help_text='Open Graph Type (e.g., website, article)', max_length=50, verbose_name='OG Type')),
                ('image', models.URLField(blank=True, help_text='Image URL for Open Graph sharing', null=True, verbose_name='OG Image')),
                ('locale', models.CharField(blank=True, help_text='Open Graph Locale (e.g., en_US)', max_length=10, null=True, verbose_name='OG Locale')),
                ('site_name', models.CharField(blank=True, help_text='Open Graph Site Name', max_length=255, null=True, verbose_name='OG Site Name')),
                ('audio', models.URLField(blank=True, help_text='Audio URL for Open Graph', null=True, verbose_name='OG Audio')),
                ('video', models.URLField(blank=True, help_text='Video URL for Open Graph', null=True, verbose_name='OG Video')),
                ('secure_url', models.URLField(blank=True, help_text='Secure URL for Open Graph', null=True, verbose_name='OG Secure URL')),
                ('image_width', models.PositiveIntegerField(blank=True, help_text='Open Graph Image Width', null=True, verbose_name='OG Image Width')),
                ('image_height', models.PositiveIntegerField(blank=True, help_text='Open Graph Image Height', null=True, verbose_name='OG Image Height')),
                ('determiner', models.CharField(blank=True, help_text='Open Graph Determiner (e.g., the, a, an)', max_length=50, null=True, verbose_name='OG Determiner')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='og_meta', to='pages.pages')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalSEOFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_ld_schema', models.JSONField(blank=True, help_text='Structured data in JSON-LD format for SEO', null=True, verbose_name='JSON-LD Schema')),
                ('robots_txt', models.TextField(blank=True, help_text='Custom robots.txt content for SEO', null=True, verbose_name='Robots.txt')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_seo', to='pages.pages')),
            ],
        ),
        migrations.AddField(
            model_name='pages',
            name='seo_keywords',
            field=models.ManyToManyField(blank=True, help_text='Keywords related to this page for SEO', related_name='pages', to='pages.seokeyword', verbose_name='SEO Keywords'),
        ),
        migrations.CreateModel(
            name='TwitterCardMetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(default='summary_large_image', help_text='Type of Twitter Card (summary, summary_large_image, etc.)', max_length=20, verbose_name='Twitter Card Type')),
                ('title', models.CharField(blank=True, help_text='Title for Twitter Card', max_length=255, null=True, verbose_name='Twitter Card Title')),
                ('description', models.TextField(blank=True, help_text='Description for Twitter Card', null=True, verbose_name='Twitter Card Description')),
                ('image', models.URLField(blank=True, help_text='Image URL for Twitter Card', null=True, verbose_name='Twitter Card Image')),
                ('site', models.CharField(blank=True, help_text='Twitter site handle (e.g., @YourSiteHandle)', max_length=255, null=True, verbose_name='Twitter Site Handle')),
                ('creator', models.CharField(blank=True, help_text='Twitter creator handle (e.g., @CreatorHandle)', max_length=255, null=True, verbose_name='Twitter Creator Handle')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_meta', to='pages.pages')),
            ],
        ),
    ]
