#############################################################################
############ DJANGO REST FRAMEWORK TEST DOCKERFILE CONFIGURATION ############
#############################################################################

# PYTHON 3.12 SLIM IMAGE
FROM python:3.12-slim

# PYTHON ENVIRONMENT VARIABLES
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# SET WORKING DIRECTORY INSIDE THE CONTAINER
WORKDIR /app/backend

# UPGRADE SYSTEM && NEED PACKENGS
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        gcc \
        python3-dev \
        libjpeg-dev \
        zlib1g-dev \
        default-libmysqlclient-dev \
        pkg-config \
        netcat-openbsd \
        curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# COPY REQUIREMENTS.TXT
COPY requirements/test.txt /app/backend/requirements/test.txt

# REQUIREMENTS.TXT ALL PACKENGS INSTALL
RUN pip install --upgrade pip && \
    pip install -r /app/backend/requirements/test.txt

# ADDITIONAL PYTHON PACKAGES
RUN pip install \
    daphne \
    redis

# COPY APPLICATION CODE
COPY . .

# EXPOSE PORT
EXPOSE 8000

# START ASGI APP WITH DAPHNE SERVER
CMD ["daphne", "-p", "8000", "-b", "0.0.0.0", "app.asgi:application"]
