# Generated by Django 5.2.7 on 2025-11-07 07:14

import django.core.validators
import utils.validate_image_size
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Enter your website copy right text...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Copy Right Text')),
            ],
        ),
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, help_text='Upload your website favicon...', null=True, upload_to='favicon/', validators=[utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Favicon')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload your website logo...', null=True, upload_to='logo/', validators=[utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Logo')),
                ('alt_text', models.CharField(blank=True, help_text='Enter your logo alt text...', max_length=180, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Logo ALT Text')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, help_text='Upload your website payment logo...', null=True, upload_to='payment-logo/', verbose_name='Payment Logo')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter your website socail link name...', max_length=180, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Socail Link Name')),
                ('url', models.URLField(blank=True, help_text='Enter your website socail link url...', max_length=280, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Socail Link URL')),
            ],
        ),
    ]
