# Generated by Django 5.2.7 on 2025-11-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copyright',
            options={'verbose_name': 'Copy-Right', 'verbose_name_plural': 'Copy-Right'},
        ),
        migrations.AlterModelOptions(
            name='favicon',
            options={'verbose_name': 'Favicon', 'verbose_name_plural': 'Favicon'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Logo', 'verbose_name_plural': 'Logo'},
        ),
        migrations.AlterModelOptions(
            name='paymentlogo',
            options={'verbose_name': 'Payment-Logo', 'verbose_name_plural': 'Payment-Logo'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'Social-Link', 'verbose_name_plural': 'Social-Link'},
        ),
    ]
