# Generated by Django 5.2.7 on 2025-11-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_copyright_options_alter_favicon_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1', models.IntegerField(verbose_name='Number 1')),
                ('number_2', models.IntegerField(verbose_name='Number 2')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentLogo',
        ),
    ]
