# Generated by Django 5.2.7 on 2025-11-11 10:48

import django.core.validators
import django.db.models.deletion
import utils.validate_image_extension
import utils.validate_image_size
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your faq title...', max_length=280, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Title')),
                ('image', models.ImageField(help_text='Upload your faq image...', upload_to='faq/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload your service image...', upload_to='services', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Image')),
                ('title', models.CharField(help_text='Enter your service title...', max_length=280, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Title')),
                ('slug', models.SlugField(editable=False, max_length=280, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Enter your service description...', null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload your service item image...', upload_to='services', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Image')),
                ('title', models.CharField(help_text='Enter your service title...', max_length=280, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Enter your service description...', null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItemMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_title', models.CharField(blank=True, help_text='Enter your service main normal title...', max_length=280, null=True, verbose_name='Normal Title')),
                ('span_title', models.CharField(blank=True, help_text='Enter your service main normal span title...', max_length=280, null=True, verbose_name='Span Title')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePageTopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your service page top bar title...', max_length=280, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Enter your service page top bar description...', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service Page Top Bar',
                'verbose_name_plural': 'Service Page Top Bar',
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Enter your faq item question...', max_length=280, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Question')),
                ('answer', models.TextField(help_text='Enter your faq item answer...', unique=True, verbose_name='Answer')),
                ('faq', models.ForeignKey(help_text='Select the FAQ this item belongs to...', on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='services.faq', verbose_name='Faq')),
            ],
        ),
    ]
