############################################################
"""
Base settings for app project.
Generated by 'django-admin startproject' using Django 5.2.7
"""
############################################################
import os
import environ
from pathlib import Path
from app.settings.unfold import UNFOLD

# BASE DIR
BASE_DIR = Path('/app/') \
    if '/opt/' in str(Path(__file__).resolve()) \
    else Path(__file__).resolve().parent.parent.parent

# LOAD ENV FILE
try:
    from dotenv import load_dotenv
    app_env = os.environ.get('ENV', 'dev')
    if app_env == 'dev':
        load_dotenv(BASE_DIR / '.env.dev')
    elif app_env == 'test':
        load_dotenv(BASE_DIR, '.env.test')
    elif app_env == 'prod':
        load_dotenv(BASE_DIR, '.env.prod')
    else:
        raise Exception('Unknown ENV value')
except:
    print('Cannot load dotenv variables. Is python-dotenv package installed?')

# LOAD ENVIRON
env = environ.Env()

# INSTALLED APPS
INSTALLED_APPS = [
    'unfold',
    'ckeditor',
    'ckeditor_uploader',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'configuration',
    'pages',
    'homepage',
    'services',
    'features',
]

# MIDDLEWARE
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

# TEMPLATES
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'
ASGI_APPLICATION = 'app.asgi.application'

# AUTH PASSWORD VALIDATORS
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Dhaka'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS SETTINGS
CORS_URLS_REGEX = r'^/api/.*$'
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS =True

# CKEDITOR UPLOAD PATH
CKEDITOR_UPLOAD_PATH = 'uploads/'

# CKEDITOR CONFIGS
CKEDITOR_CONFIGS = {
    'default': {
        'height': 300,
        'width': '100%',
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Source', 'Maximize', 'ShowBlocks', 'Preview', 'Templates'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord'],
            ['Undo', 'Redo', 'Find', 'Replace', 'SelectAll', 'RemoveFormat'],
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],
            ['NumberedList', 'BulletedList', 'Outdent', 'Indent', 'Blockquote', 'CreateDiv'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'UploadImage', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['CodeSnippet', 'Embed', 'Language'],
        ],
        'extraPlugins': ','.join([
            'uploadimage', 'image2', 'autogrow', 'justify', 'codesnippet', 'embed', 'colorbutton', 'colordialog',
            'font', 'showblocks', 'preview', 'print', 'templates', 'find', 'selectall', 'clipboard', 'pastefromword',
            'language'
        ]),
        'removePlugins': 'stylesheetparser',
        'allowedContent': True,
        'autoParagraph': False,
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'filebrowserBrowseUrl': '/ckeditor/browse/',
    }
}

# ======== ADMIN UI UNFOLD ============
UNFOLD=UNFOLD
